name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  provider: ^6.1.2
  socket_io_client: ^3.1.1
  google_fonts: ^6.2.1 
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  stream_video: ^0.9.2
  stream_video_flutter: ^0.9.2
  stream_video_push_notification: ^0.9.2
  flutter_callkit_incoming: ^2.5.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
